import { Category } from '../models/Category.js';
import { deleteImage, uploadBuffer } from '../services/imageService.js';
import { slugify } from '../utils/slugify.js';

const serialize = category => ({ ...category, id: category._id.toString(), image: category.image?.url });
export async function listCategories(_req, res, next) { try { res.json((await Category.find({ active: true }).sort({ order: 1 }).lean()).map(serialize)); } catch (error) { next(error); } }
export async function listAdminCategories(_req, res, next) { try { res.json((await Category.find().sort({ order: 1 }).lean()).map(serialize)); } catch (error) { next(error); } }
export async function createCategory(req, res, next) { try { if (!req.file) return res.status(400).json({ message: 'La imagen es obligatoria' }); const slug = slugify(req.body.name); const upload = await uploadBuffer(req.file.buffer, { folder: 'chosen/categories', publicId: slug }); const category = await Category.create({ name: req.body.name, slug, order: Number(req.body.order || 0), active: req.body.active === 'true' || req.body.active === true, image: { url: upload.secure_url, publicId: upload.public_id } }); res.status(201).json(serialize(category.toObject())); } catch (error) { next(error); } }
export async function updateCategory(req, res, next) { try { const current = await Category.findById(req.params.id); if (!current) return res.status(404).json({ message: 'Categoría no encontrada' }); const slug = slugify(req.body.name); const data = { name: req.body.name, slug, order: Number(req.body.order || 0), active: req.body.active === 'true' || req.body.active === true }; if (req.file) { const upload = await uploadBuffer(req.file.buffer, { folder: 'chosen/categories', publicId: slug }); data.image = { url: upload.secure_url, publicId: upload.public_id }; if (current.image.publicId !== upload.public_id) await deleteImage(current.image.publicId); } const category = await Category.findByIdAndUpdate(req.params.id, data, { returnDocument: 'after', runValidators: true }).lean(); res.json(serialize(category)); } catch (error) { next(error); } }
export async function deleteCategory(req, res, next) { try { const category = await Category.findByIdAndDelete(req.params.id); if (!category) return res.status(404).json({ message: 'Categoría no encontrada' }); await deleteImage(category.image?.publicId); res.json({ message: 'Categoría eliminada' }); } catch (error) { next(error); } }
