import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { checkoutService } from '../services/checkoutService';
import { money } from '../utils/currency';

const emptyCustomer={name:'',email:'',phone:'',address:'',city:'',province:'Buenos Aires',postalCode:''};
const fields={name:'Nombre y apellido',email:'Email',phone:'Teléfono',address:'Dirección y altura',city:'Localidad',province:'Provincia',postalCode:'Código postal'};

export function CheckoutPage({cart}){
  const[customer,setCustomer]=useState(emptyCustomer),[settings,setSettings]=useState(null),[shippingMethod,setShippingMethod]=useState('local'),[paymentMethod,setPaymentMethod]=useState('mercadopago');
  const[quote,setQuote]=useState(null),[quoting,setQuoting]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{checkoutService.settings().then(data=>{setSettings(data);if(!data.shipping?.localDeliveryEnabled)setShippingMethod('delivery');if(!data.mercadoPago?.enabled&&data.transfer?.enabled)setPaymentMethod('transfer');}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(shippingMethod!=='local'||!customer.address.trim()||!customer.city.trim()||!customer.province.trim()){setQuote(null);return;}const timer=setTimeout(async()=>{try{setQuoting(true);setError('');setQuote(await checkoutService.quote(customer));}catch(e){setQuote(null);setError(e.message);}finally{setQuoting(false);}},700);return()=>clearTimeout(timer);},[shippingMethod,customer.address,customer.city,customer.province,customer.postalCode]);
  const free=settings?.shipping?.freeThreshold>0&&cart.summary.total>=settings.shipping.freeThreshold;
  const shippingCost=shippingMethod==='pickup'||free?0:shippingMethod==='local'?Number(quote?.cost||0):Number(settings?.shipping?.flatRate||0);
  const submit=async event=>{event.preventDefault();if(shippingMethod==='local'&&!quote?.available){setError('Completá la dirección y esperá el cálculo de la entrega local.');return;}try{setLoading(true);setError('');const response=await checkoutService.create({customer,items:cart.items.map(item=>({id:item.id,quantity:item.qty})),shippingMethod,paymentMethod});if(response.checkoutUrl)window.location.assign(response.checkoutUrl);else{setResult(response);cart.clear();}}catch(e){setError(e.message);}finally{setLoading(false);}};
  if(!cart.items.length&&!result)return <main className="page container checkout-empty"><h1>Tu carrito está vacío</h1><Link className="btn btn-dark" to="/productos">VER PRODUCTOS</Link></main>;
  if(result)return <main className="page container checkout-success"><span className="eyebrow">PEDIDO RECIBIDO</span><h1>Transferencia pendiente</h1><p>Tu pedido es <strong>#{result.orderId.slice(-6).toUpperCase()}</strong>. Transferí {money(result.total)} y envianos el comprobante.</p><div><b>Titular</b><span>{result.transfer.holder||'A confirmar'}</span><b>Alias</b><span>{result.transfer.alias||'A confirmar'}</span>{result.transfer.cbu&&<><b>CBU/CVU</b><span>{result.transfer.cbu}</span></>}</div></main>;
  return <main className="page container checkout-page"><div><span className="eyebrow">FINALIZAR COMPRA</span><h1>Datos de entrega</h1><form id="checkout-form" className="checkout-form" onSubmit={submit}>{error&&<p className="admin-error">{error}</p>}<div className="checkout-fields">{Object.entries(fields).map(([key,label])=><label key={key}>{label}<input type={key==='email'?'email':'text'} value={customer[key]} onChange={event=>setCustomer({...customer,[key]:event.target.value})} required/></label>)}</div><fieldset><legend>Envío</legend>
    {settings?.shipping?.localDeliveryEnabled&&<label><input type="radio" checked={shippingMethod==='local'} onChange={()=>setShippingMethod('local')}/> Entrega local Chosen <strong>{quoting?'Calculando…':quote?.available?`${money(quote.cost)} · ${quote.distanceKm} km`:quote&&!quote.available?`Fuera del radio (${quote.distanceKm} km)`:'Completá tu dirección'}</strong></label>}
    <label><input type="radio" checked={shippingMethod==='delivery'} onChange={()=>setShippingMethod('delivery')}/> Envío por correo <strong>{settings?.shipping?.flatRate?money(settings.shipping.flatRate):'A coordinar'}</strong></label>
    {settings?.shipping?.pickupEnabled&&<label><input type="radio" checked={shippingMethod==='pickup'} onChange={()=>setShippingMethod('pickup')}/> {settings.shipping.pickupLabel} <strong>Gratis</strong></label>}
  </fieldset><fieldset><legend>Pago</legend>{settings?.mercadoPago?.enabled&&<label><input type="radio" checked={paymentMethod==='mercadopago'} onChange={()=>setPaymentMethod('mercadopago')}/> Mercado Pago</label>}{settings?.transfer?.enabled&&<label><input type="radio" checked={paymentMethod==='transfer'} onChange={()=>setPaymentMethod('transfer')}/> Transferencia bancaria</label>}</fieldset></form></div>
  <aside className="checkout-summary"><h2>Tu pedido</h2>{cart.items.map(item=><div key={item.id}><span>{item.qty} × {item.name}</span><b>{money(item.qty*item.price)}</b></div>)}<div><span>Envío</span><b>{shippingMethod==='local'&&!quote?.available?'—':shippingCost?money(shippingCost):'Gratis'}</b></div><div className="checkout-total"><span>Total</span><strong>{money(cart.summary.total+shippingCost)}</strong></div><button form="checkout-form" className="btn btn-dark wide" disabled={loading||quoting||(shippingMethod==='local'&&!quote?.available)}>{loading?'PROCESANDO…':quoting?'CALCULANDO ENVÍO…':'CONTINUAR AL PAGO'}</button></aside></main>;
}
