import { useEffect, useState } from 'react';
import { adminService } from '../../services/adminService';

const shippingDefaults={flatRate:0,freeThreshold:0,pickupEnabled:true,pickupLabel:'Retiro a coordinar',localDeliveryEnabled:true,originAddress:'Gabriel Miró 774, Bella Vista, Buenos Aires, Argentina',fuelPrice:2169,vehicleKmPerLiter:10,operatingMultiplier:1.5,baseDeliveryFee:2500,minimumDeliveryFee:3500,maximumLocalKm:15};
const initial={shipping:shippingDefaults,transfer:{enabled:true,alias:'',cbu:'',holder:''},mercadoPago:{enabled:true}};

export function AdminSettingsPage(){
  const[form,setForm]=useState(initial),[message,setMessage]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{adminService.settings().then(data=>setForm({shipping:{...shippingDefaults,...data.shipping},transfer:{...initial.transfer,...data.transfer},mercadoPago:{...initial.mercadoPago,...data.mercadoPago}})).catch(e=>setError(e.message));},[]);
  const section=(name,key,value)=>setForm(current=>({...current,[name]:{...current[name],[key]:value}}));
  const submit=async event=>{event.preventDefault();try{setSaving(true);setError('');setMessage('');const data=await adminService.saveSettings(form);setForm({shipping:{...shippingDefaults,...data.shipping},transfer:{...initial.transfer,...data.transfer},mercadoPago:{...initial.mercadoPago,...data.mercadoPago}});setMessage('Configuración guardada.');}catch(e){setError(e.message);}finally{setSaving(false);}};
  const perKm=Math.ceil(((2*Number(form.shipping.fuelPrice||0)/Number(form.shipping.vehicleKmPerLiter||1))*Number(form.shipping.operatingMultiplier||1))/100)*100;
  return <section className="admin-page"><header><div><span>CHECKOUT</span><h1>Envíos y pagos</h1><p>Configurá las opciones que verá el cliente al finalizar su compra.</p></div></header><form className="admin-form admin-settings" onSubmit={submit}>
    {error&&<p className="admin-error">{error}</p>}{message&&<p className="admin-success">{message}</p>}
    <h2>Entrega local automática</h2><label><input type="checkbox" checked={form.shipping.localDeliveryEnabled} onChange={e=>section('shipping','localDeliveryEnabled',e.target.checked)}/> Habilitar entrega propia por distancia</label>
    <label>Dirección de salida<input value={form.shipping.originAddress} onChange={e=>section('shipping','originAddress',e.target.value)}/></label>
    <div className="admin-form-row"><label>Nafta por litro<input type="number" min="0" value={form.shipping.fuelPrice} onChange={e=>section('shipping','fuelPrice',e.target.value)}/></label><label>Rendimiento (km/litro)<input type="number" min="1" step="0.1" value={form.shipping.vehicleKmPerLiter} onChange={e=>section('shipping','vehicleKmPerLiter',e.target.value)}/></label></div>
    <div className="admin-form-row"><label>Cargo base<input type="number" min="0" value={form.shipping.baseDeliveryFee} onChange={e=>section('shipping','baseDeliveryFee',e.target.value)}/></label><label>Cargo mínimo<input type="number" min="0" value={form.shipping.minimumDeliveryFee} onChange={e=>section('shipping','minimumDeliveryFee',e.target.value)}/></label></div>
    <div className="admin-form-row"><label>Margen operativo<input type="number" min="1" step="0.1" value={form.shipping.operatingMultiplier} onChange={e=>section('shipping','operatingMultiplier',e.target.value)}/></label><label>Radio máximo (km)<input type="number" min="1" step="0.5" value={form.shipping.maximumLocalKm} onChange={e=>section('shipping','maximumLocalKm',e.target.value)}/></label></div>
    <small>Valor variable: aproximadamente ${perKm.toLocaleString('es-AR')} por km. Incluye combustible de ida y vuelta y margen operativo.</small>
    <h2>Correo y retiro</h2><div className="admin-form-row"><label>Tarifa nacional<input type="number" min="0" value={form.shipping.flatRate} onChange={e=>section('shipping','flatRate',e.target.value)}/></label><label>Envío gratis desde<input type="number" min="0" value={form.shipping.freeThreshold} onChange={e=>section('shipping','freeThreshold',e.target.value)}/></label></div>
    <label><input type="checkbox" checked={form.shipping.pickupEnabled} onChange={e=>section('shipping','pickupEnabled',e.target.checked)}/> Permitir retiro</label><label>Nombre del retiro<input value={form.shipping.pickupLabel} onChange={e=>section('shipping','pickupLabel',e.target.value)}/></label>
    <h2>Transferencia</h2><label><input type="checkbox" checked={form.transfer.enabled} onChange={e=>section('transfer','enabled',e.target.checked)}/> Habilitar transferencia</label><label>Titular<input value={form.transfer.holder} onChange={e=>section('transfer','holder',e.target.value)}/></label><div className="admin-form-row"><label>Alias<input value={form.transfer.alias} onChange={e=>section('transfer','alias',e.target.value)}/></label><label>CBU/CVU<input value={form.transfer.cbu} onChange={e=>section('transfer','cbu',e.target.value)}/></label></div>
    <h2>Mercado Pago</h2><label><input type="checkbox" checked={form.mercadoPago.enabled} onChange={e=>section('mercadoPago','enabled',e.target.checked)}/> Habilitar Mercado Pago</label><small>El Access Token se guarda de forma segura en Render.</small><button className="admin-primary" disabled={saving}>{saving?'GUARDANDO…':'GUARDAR CONFIGURACIÓN'}</button>
  </form></section>;
}
